AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Abnormal Sensor Data Processing Microservices

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs22.x
    Environment:
      Variables:
        LOGGER_LEVEL: debug
        TZ: Asia/Jerusalem
    Layers:
      - !Ref PinoLoggerLayer
    Architectures:
      - x86_64

Parameters:
  IngestStreamTopicArn:
    Type: String
    Description: ARN of the ingest stream SNS topic

Resources:
  # DynamoDB Table
  SensorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SensorsNormalValues
      AttributeDefinitions:
        - AttributeName: sensorId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: sensorId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # Pino Logger Layer
  PinoLoggerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pino-logger-layer
      ContentUri: ../layers/pino-logger/
      CompatibleRuntimes:
        - nodejs22.x

  # SNS Topics
  LowSensorDataTopic:
    Type: AWS::SNS::Topic
  HighSensorDataTopic:
    Type: AWS::SNS::Topic

  # Lambda Functions
  SensorDataProviderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sensor-data-provider
      CodeUri: sensor-data-provider/
      Handler: app.handler

  AbnormalSensorDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: abnormal-sensor-data
      CodeUri: abnormal-sensor-data/
      Handler: app.lambdaHandler
      Events:
        IngestStreamSubscription:
          Type: SNS
          Properties:
            Topic: !Ref IngestStreamTopicArn
      Environment:
        Variables:
          LOW_SENSOR_DATA_TOPIC_ARN: !Ref LowSensorDataTopic
          HIGH_SENSOR_DATA_TOPIC_ARN: !Ref HighSensorDataTopic
          SENSOR_DATA_PROVIDER_FUNCTION_NAME: !Ref SensorDataProviderFunction
          STALE_TIME: "2"
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt LowSensorDataTopic.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt HighSensorDataTopic.TopicName
        - LambdaInvokePolicy:
            FunctionName: !Ref SensorDataProviderFunction

  LowDataProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: low-data-processor
      CodeUri: low-data-processor/
      Handler: app.lambdaHandler
      Events:
        LowSensorDataSubscription:
          Type: SNS
          Properties:
            Topic: !Ref LowSensorDataTopic
      Environment:
        Variables:
          TABLE_NAME: !Ref SensorsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SensorsTable

  HighDataProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: high-data-processor
      CodeUri: high-data-processor/
      Handler: app.lambdaHandler
      Events:
        HighSensorDataSubscription:
          Type: SNS
          Properties:
            Topic: !Ref HighSensorDataTopic
      Environment:
        Variables:
          TABLE_NAME: !Ref SensorsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SensorsTable

Outputs:
  LowSensorDataTopicArn:
    Value: !Ref LowSensorDataTopic
  HighSensorDataTopicArn:
    Value: !Ref HighSensorDataTopic
  SensorsTableName:
    Value: !Ref SensorsTable
  AbnormalSensorDataFunctionArn:
    Value: !GetAtt AbnormalSensorDataFunction.Arn
  LowDataProcessorFunctionArn:
    Value: !GetAtt LowDataProcessorFunction.Arn
  HighDataProcessorFunctionArn:
    Value: !GetAtt HighDataProcessorFunction.Arn
  SensorDataProviderFunctionArn:
    Value: !GetAtt SensorDataProviderFunction.Arn
